### ISSUE TITLE
Build fails on CentOS 7

### ISSUE THREAD

**Issue by rhc54** [intel/opa-ff#11]
I'm trying to build on CentOS 7, which is viewed as the same as RHEL 7 by most build systems. I found that I had to make one change just to get past the initial check:
```diff
diff --git a/update_opa_spec.sh b/update_opa_spec.sh
index 00a7007..b48fd5c 100755
--- a/update_opa_spec.sh
+++ b/update_opa_spec.sh
@@ -50,7 +50,7 @@ fi
 
 source ./OpenIb_Host/ff_filegroups.sh
 
-if [ "$id" = "rhel" ]
+if [ "$id" = "rhel" -o "$id" = "centos" ]
 then
        GE_7_4=$(echo "$versionid >= 7.4" | bc)
        if [ $GE_7_4 = 1 ]
```

With that, the rpm builds (though with lots of warnings about misleading indentation) until it hits an error towards the very end:
```
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id -m --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 110000000 /home/rhc/rpmbuild/BUILD/opa-10.6.0.0
extracting debug info from /home/rhc/rpmbuild/BUILDROOT/opa-10.6.0.0-131.el7.centos.x86_64/usr/bin/opa_osd_dump
*** ERROR: No build ID note found in /home/rhc/rpmbuild/BUILDROOT/opa-10.6.0.0-131.el7.centos.x86_64/usr/bin/opa_osd_dump
error: Bad exit status from /var/tmp/rpm-tmp.gvtQDj (%install)

```
Any suggestions on how to get past this problem?

**Comment by sjb017** [comment]
Hello Ralph,

Thanks for your feedback.

We will have the change to your if statement (adding the condition for centos) in our next upstream version of opa-ff.

Regaring the problem with find-debuginfo, you can try adding this line to opa-ff/opa-ff.spec.in, just before the line with “__RPM_DEBUG” (~ line 13) to suppress the creation of the debug RPM.

%define debug_package %{nil}

In the meantime I will open an internal bug report and we will pursue a solution.

Scott Breyer
Intel Corporation

**Comment by rhc54** [comment]
Thanks - that worked fine!
