### ISSUE TITLE
v10.9.0.2.1

### ISSUE THREAD

**Issue by bsmith94** [intel/opa-ff#21]
Is [v10.9.0.2.1](https://github.com/intel/opa-ff/releases/tag/v10.9.0.2.1) the correct version number? I see a 10.9.0.1-2 in IFS 10.9.0.1.5, which is the latest release on Intel's website. 

Just checking. Thanks.

**Comment by bsmith94** [comment]
That is the version in opa-ff.spec.in, so it does appear to be correct.

**Comment by sjb017** [comment]
Yes, it is correct. Because of an anomaly, we were unable to push 10.9.0.1-2 and needed to rebuild as 10.9.0.2-1, which did not appear in an IFS release.
