### ISSUE TITLE
'validatevlcreditloops' option in opareport

### ISSUE THREAD

**Issue by onewayforever** [intel/opa-ff#6]
Hi,
    I checked the opareport code for validatevlcreditloops option

  if (report & REPORT_VALIDATECREDITLOOPS || report & REPORT_VALIDATEVLCREDITLOOPS)
                ShowValidateCreditLoopsReport(&focus, format, 0, detail);

  It seems that validatevlcreditloops option have not been implemented, and can not use this tool to validate credit loops with VL switching yet?

**Comment by sjb017** [comment]
Hello, thank you for your inquiry.

Why do you think that the validatevlcreditloops option is not implemented? It appears to be in the code. Are you getting an error when you try to use it? If so, please provide more detail.

Thank you,
Scott Breyer
Intel Corporation
Maintainer of 01org/opa-ff

**Comment by onewayforever** [comment]
I think these two options are using the same function with same arguments, and the result will be the same.

Below is the output of the test

# fabric_sim -t torus -d 4x4 -I 2
# opareport -o validatevlcreditloops 

Validate Credit Loop Routes
Fabric summary: 656 devices, 640 HFIs, 16 switches,
	1408 connections, 419200 routing decisions,
	408960 analyzed routes, 0 incomplete routes
Deadlock detected in routes (Credit loops detected)
LINK 2 (MOOSE_STL_SWITCH1 (1,0):7 to MOOSE_STL_SWITCH5 (1,1):8 VL:0) is in a CYCLE of 4:
    0: LINK 2 (MOOSE_STL_SWITCH1 (1,0):7 to MOOSE_STL_SWITCH5 (1,1):8 VL:0)
    1: LINK 12 (MOOSE_STL_SWITCH5 (1,1):3 to MOOSE_STL_SWITCH6 (2,1):4 VL:0)
    2: LINK 22 (MOOSE_STL_SWITCH6 (2,1):8 to MOOSE_STL_SWITCH2 (2,0):7 VL:0)
    3: LINK 39 (MOOSE_STL_SWITCH2 (2,0):4 to MOOSE_STL_SWITCH1 (1,0):3 VL:0)
LINK 3 (MOOSE_STL_SWITCH1 (1,0):3 to MOOSE_STL_SWITCH2 (2,0):4 VL:0) is in a CYCLE of 4:
    0: LINK 3 (MOOSE_STL_SWITCH1 (1,0):3 to MOOSE_STL_SWITCH2 (2,0):4 VL:0)
    1: LINK 50 (MOOSE_STL_SWITCH2 (2,0):5 to MOOSE_STL_SWITCH6 (2,1):6 VL:0)
    2: LINK 58 (MOOSE_STL_SWITCH6 (2,1):2 to MOOSE_STL_SWITCH5 (1,1):1 VL:0)
    3: LINK 79 (MOOSE_STL_SWITCH5 (1,1):6 to MOOSE_STL_SWITCH1 (1,0):5 VL:0)
LINK 4 (MOOSE_STL_SWITCH1 (1,0):1 to MOOSE_STL_SWITCH2 (2,0):2 VL:0) is in a CYCLE of 4:
    0: LINK 4 (MOOSE_STL_SWITCH1 (1,0):1 to MOOSE_STL_SWITCH2 (2,0):2 VL:0)
    1: LINK 50 (MOOSE_STL_SWITCH2 (2,0):5 to MOOSE_STL_SWITCH6 (2,1):6 VL:0)
    2: LINK 58 (MOOSE_STL_SWITCH6 (2,1):2 to MOOSE_STL_SWITCH5 (1,1):1 VL:0)
    3: LINK 79 (MOOSE_STL_SWITCH5 (1,1):6 to MOOSE_STL_SWITCH1 (1,0):5 VL:0)
LINK 7 (MOOSE_STL_SWITCH12 (0,3):5 to MOOSE_STL_SWITCH0 (0,0):6 VL:0) is in a CYCLE of 4:
    0: LINK 7 (MOOSE_STL_SWITCH12 (0,3):5 to MOOSE_STL_SWITCH0 (0,0):6 VL:0)
    1: LINK 0 (MOOSE_STL_SWITCH0 (0,0):3 to MOOSE_STL_SWITCH1 (1,0):4 VL:0)
    2: LINK 6 (MOOSE_STL_SWITCH1 (1,0):6 to MOOSE_STL_SWITCH13 (1,3):5 VL:0)
    3: LINK 117 (MOOSE_STL_SWITCH13 (1,3):2 to MOOSE_STL_SWITCH12 (0,3):1 VL:0)
LINK 8 (MOOSE_STL_SWITCH12 (0,3):7 to MOOSE_STL_SWITCH0 (0,0):8 VL:0) is in a CYCLE of 4:
    0: LINK 8 (MOOSE_STL_SWITCH12 (0,3):7 to MOOSE_STL_SWITCH0 (0,0):8 VL:0)
    1: LINK 69 (MOOSE_STL_SWITCH0 (0,0):4 to MOOSE_STL_SWITCH3 (3,0):3 VL:0)
    2: LINK 77 (MOOSE_STL_SWITCH3 (3,0):8 to MOOSE_STL_SWITCH15 (3,3):7 VL:0)
    3: LINK 107 (MOOSE_STL_SWITCH15 (3,3):3 to MOOSE_STL_SWITCH12 (0,3):4 VL:0)
LINK 9 (MOOSE_STL_SWITCH4 (0,1):6 to MOOSE_STL_SWITCH0 (0,0):5 VL:0) is in a CYCLE of 4:
    0: LINK 9 (MOOSE_STL_SWITCH4 (0,1):6 to MOOSE_STL_SWITCH0 (0,0):5 VL:0)
    1: LINK 0 (MOOSE_STL_SWITCH0 (0,0):3 to MOOSE_STL_SWITCH1 (1,0):4 VL:0)
    2: LINK 1 (MOOSE_STL_SWITCH1 (1,0):5 to MOOSE_STL_SWITCH5 (1,1):6 VL:0)
    3: LINK 14 (MOOSE_STL_SWITCH5 (1,1):2 to MOOSE_STL_SWITCH4 (0,1):1 VL:0)
LINK 10 (MOOSE_STL_SWITCH3 (3,0):3 to MOOSE_STL_SWITCH0 (0,0):4 VL:0) is in a CYCLE of 4:
    0: LINK 10 (MOOSE_STL_SWITCH3 (3,0):3 to MOOSE_STL_SWITCH0 (0,0):4 VL:0)
    1: LINK 0 (MOOSE_STL_SWITCH0 (0,0):3 to MOOSE_STL_SWITCH1 (1,0):4 VL:0)
    2: LINK 3 (MOOSE_STL_SWITCH1 (1,0):3 to MOOSE_STL_SWITCH2 (2,0):4 VL:0)
    3: LINK 38 (MOOSE_STL_SWITCH2 (2,0):3 to MOOSE_STL_SWITCH3 (3,0):4 VL:0)
LINK 11 (MOOSE_STL_SWITCH3 (3,0):1 to MOOSE_STL_SWITCH0 (0,0):2 VL:0) is in a CYCLE of 4:
    0: LINK 11 (MOOSE_STL_SWITCH3 (3,0):1 to MOOSE_STL_SWITCH0 (0,0):2 VL:0)
    1: LINK 0 (MOOSE_STL_SWITCH0 (0,0):3 to MOOSE_STL_SWITCH1 (1,0):4 VL:0)
    2: LINK 3 (MOOSE_STL_SWITCH1 (1,0):3 to MOOSE_STL_SWITCH2 (2,0):4 VL:0)
    3: LINK 38 (MOOSE_STL_SWITCH2 (2,0):3 to MOOSE_STL_SWITCH3 (3,0):4 VL:0)
LINK 13 (MOOSE_STL_SWITCH5 (1,1):1 to MOOSE_STL_SWITCH6 (2,1):2 VL:0) is in a CYCLE of 4:
    0: LINK 13 (MOOSE_STL_SWITCH5 (1,1):1 to MOOSE_STL_SWITCH6 (2,1):2 VL:0)
    1: LINK 43 (MOOSE_STL_SWITCH6 (2,1):1 to MOOSE_STL_SWITCH7 (3,1):2 VL:0)
    2: LINK 61 (MOOSE_STL_SWITCH7 (3,1):1 to MOOSE_STL_SWITCH4 (0,1):2 VL:0)
    3: LINK 93 (MOOSE_STL_SWITCH4 (0,1):1 to MOOSE_STL_SWITCH5 (1,1):2 VL:0)
LINK 18 (MOOSE_STL_SWITCH13 (1,3):5 to MOOSE_STL_SWITCH1 (1,0):6 VL:0) is in a CYCLE of 4:
    0: LINK 18 (MOOSE_STL_SWITCH13 (1,3):5 to MOOSE_STL_SWITCH1 (1,0):6 VL:0)
    1: LINK 1 (MOOSE_STL_SWITCH1 (1,0):5 to MOOSE_STL_SWITCH5 (1,1):6 VL:0)
    2: LINK 15 (MOOSE_STL_SWITCH5 (1,1):5 to MOOSE_STL_SWITCH9 (1,2):6 VL:0)
    3: LINK 120 (MOOSE_STL_SWITCH9 (1,2):5 to MOOSE_STL_SWITCH13 (1,3):6 VL:0)
LINK 19 (MOOSE_STL_SWITCH13 (1,3):7 to MOOSE_STL_SWITCH1 (1,0):8 VL:0) is in a CYCLE of 4:
    0: LINK 19 (MOOSE_STL_SWITCH13 (1,3):7 to MOOSE_STL_SWITCH1 (1,0):8 VL:0)
    1: LINK 2 (MOOSE_STL_SWITCH1 (1,0):7 to MOOSE_STL_SWITCH5 (1,1):8 VL:0)
    2: LINK 16 (MOOSE_STL_SWITCH5 (1,1):7 to MOOSE_STL_SWITCH9 (1,2):8 VL:0)
    3: LINK 114 (MOOSE_STL_SWITCH9 (1,2):7 to MOOSE_STL_SWITCH13 (1,3):8 VL:0)
LINK 20 (MOOSE_STL_SWITCH2 (2,0):2 to MOOSE_STL_SWITCH1 (1,0):1 VL:0) is in a CYCLE of 4:
    0: LINK 20 (MOOSE_STL_SWITCH2 (2,0):2 to MOOSE_STL_SWITCH1 (1,0):1 VL:0)
    1: LINK 1 (MOOSE_STL_SWITCH1 (1,0):5 to MOOSE_STL_SWITCH5 (1,1):6 VL:0)
    2: LINK 12 (MOOSE_STL_SWITCH5 (1,1):3 to MOOSE_STL_SWITCH6 (2,1):4 VL:0)
    3: LINK 22 (MOOSE_STL_SWITCH6 (2,1):8 to MOOSE_STL_SWITCH2 (2,0):7 VL:0)
LINK 24 (MOOSE_STL_SWITCH4 (0,1):3 to MOOSE_STL_SWITCH5 (1,1):4 VL:0) is in a CYCLE of 4:
    0: LINK 24 (MOOSE_STL_SWITCH4 (0,1):3 to MOOSE_STL_SWITCH5 (1,1):4 VL:0)
    1: LINK 12 (MOOSE_STL_SWITCH5 (1,1):3 to MOOSE_STL_SWITCH6 (2,1):4 VL:0)
    2: LINK 23 (MOOSE_STL_SWITCH6 (2,1):3 to MOOSE_STL_SWITCH7 (3,1):4 VL:0)
    3: LINK 95 (MOOSE_STL_SWITCH7 (3,1):3 to MOOSE_STL_SWITCH4 (0,1):4 VL:0)
LINK 25 (MOOSE_STL_SWITCH9 (1,2):8 to MOOSE_STL_SWITCH5 (1,1):7 VL:0) is in a CYCLE of 4:
    0: LINK 25 (MOOSE_STL_SWITCH9 (1,2):8 to MOOSE_STL_SWITCH5 (1,1):7 VL:0)
    1: LINK 12 (MOOSE_STL_SWITCH5 (1,1):3 to MOOSE_STL_SWITCH6 (2,1):4 VL:0)
    2: LINK 21 (MOOSE_STL_SWITCH6 (2,1):7 to MOOSE_STL_SWITCH10 (2,2):8 VL:0)
    3: LINK 28 (MOOSE_STL_SWITCH10 (2,2):4 to MOOSE_STL_SWITCH9 (1,2):3 VL:0)
LINK 29 (MOOSE_STL_SWITCH7 (3,1):4 to MOOSE_STL_SWITCH6 (2,1):3 VL:0) is in a CYCLE of 4:
    0: LINK 29 (MOOSE_STL_SWITCH7 (3,1):4 to MOOSE_STL_SWITCH6 (2,1):3 VL:0)
    1: LINK 22 (MOOSE_STL_SWITCH6 (2,1):8 to MOOSE_STL_SWITCH2 (2,0):7 VL:0)
    2: LINK 38 (MOOSE_STL_SWITCH2 (2,0):3 to MOOSE_STL_SWITCH3 (3,0):4 VL:0)
    3: LINK 78 (MOOSE_STL_SWITCH3 (3,0):7 to MOOSE_STL_SWITCH7 (3,1):8 VL:0)
LINK 35 (MOOSE_STL_SWITCH11 (3,2):4 to MOOSE_STL_SWITCH10 (2,2):3 VL:0) is in a CYCLE of 4:
    0: LINK 35 (MOOSE_STL_SWITCH11 (3,2):4 to MOOSE_STL_SWITCH10 (2,2):3 VL:0)
    1: LINK 28 (MOOSE_STL_SWITCH10 (2,2):4 to MOOSE_STL_SWITCH9 (1,2):3 VL:0)
    2: LINK 98 (MOOSE_STL_SWITCH9 (1,2):4 to MOOSE_STL_SWITCH8 (0,2):3 VL:0)
    3: LINK 108 (MOOSE_STL_SWITCH8 (0,2):4 to MOOSE_STL_SWITCH11 (3,2):3 VL:0)
LINK 36 (MOOSE_STL_SWITCH9 (1,2):3 to MOOSE_STL_SWITCH10 (2,2):4 VL:0) is in a CYCLE of 4:
    0: LINK 36 (MOOSE_STL_SWITCH9 (1,2):3 to MOOSE_STL_SWITCH10 (2,2):4 VL:0)
    1: LINK 26 (MOOSE_STL_SWITCH10 (2,2):7 to MOOSE_STL_SWITCH14 (2,3):8 VL:0)
    2: LINK 33 (MOOSE_STL_SWITCH14 (2,3):4 to MOOSE_STL_SWITCH13 (1,3):3 VL:0)
    3: LINK 96 (MOOSE_STL_SWITCH13 (1,3):8 to MOOSE_STL_SWITCH9 (1,2):7 VL:0)
LINK 40 (MOOSE_STL_SWITCH15 (3,3):4 to MOOSE_STL_SWITCH14 (2,3):3 VL:0) is in a CYCLE of 4:
    0: LINK 40 (MOOSE_STL_SWITCH15 (3,3):4 to MOOSE_STL_SWITCH14 (2,3):3 VL:0)
    1: LINK 33 (MOOSE_STL_SWITCH14 (2,3):4 to MOOSE_STL_SWITCH13 (1,3):3 VL:0)
    2: LINK 97 (MOOSE_STL_SWITCH13 (1,3):4 to MOOSE_STL_SWITCH12 (0,3):3 VL:0)
    3: LINK 109 (MOOSE_STL_SWITCH12 (0,3):4 to MOOSE_STL_SWITCH15 (3,3):3 VL:0)
LINK 45 (MOOSE_STL_SWITCH3 (3,0):4 to MOOSE_STL_SWITCH2 (2,0):3 VL:0) is in a CYCLE of 4:
    0: LINK 45 (MOOSE_STL_SWITCH3 (3,0):4 to MOOSE_STL_SWITCH2 (2,0):3 VL:0)
    1: LINK 37 (MOOSE_STL_SWITCH2 (2,0):7 to MOOSE_STL_SWITCH6 (2,1):8 VL:0)
    2: LINK 43 (MOOSE_STL_SWITCH6 (2,1):1 to MOOSE_STL_SWITCH7 (3,1):2 VL:0)
    3: LINK 59 (MOOSE_STL_SWITCH7 (3,1):6 to MOOSE_STL_SWITCH3 (3,0):5 VL:0)
LINK 46 (MOOSE_STL_SWITCH3 (3,0):2 to MOOSE_STL_SWITCH2 (2,0):1 VL:0) is in a CYCLE of 4:
    0: LINK 46 (MOOSE_STL_SWITCH3 (3,0):2 to MOOSE_STL_SWITCH2 (2,0):1 VL:0)
    1: LINK 37 (MOOSE_STL_SWITCH2 (2,0):7 to MOOSE_STL_SWITCH6 (2,1):8 VL:0)
    2: LINK 43 (MOOSE_STL_SWITCH6 (2,1):1 to MOOSE_STL_SWITCH7 (3,1):2 VL:0)
    3: LINK 59 (MOOSE_STL_SWITCH7 (3,1):6 to MOOSE_STL_SWITCH3 (3,0):5 VL:0)
LINK 51 (MOOSE_STL_SWITCH7 (3,1):2 to MOOSE_STL_SWITCH6 (2,1):1 VL:0) is in a CYCLE of 4:
    0: LINK 51 (MOOSE_STL_SWITCH7 (3,1):2 to MOOSE_STL_SWITCH6 (2,1):1 VL:0)
    1: LINK 42 (MOOSE_STL_SWITCH6 (2,1):5 to MOOSE_STL_SWITCH10 (2,2):6 VL:0)
    2: LINK 48 (MOOSE_STL_SWITCH10 (2,2):1 to MOOSE_STL_SWITCH11 (3,2):2 VL:0)
    3: LINK 65 (MOOSE_STL_SWITCH11 (3,2):6 to MOOSE_STL_SWITCH7 (3,1):5 VL:0)
LINK 53 (MOOSE_STL_SWITCH11 (3,2):2 to MOOSE_STL_SWITCH10 (2,2):1 VL:0) is in a CYCLE of 6:
    0: LINK 53 (MOOSE_STL_SWITCH11 (3,2):2 to MOOSE_STL_SWITCH10 (2,2):1 VL:0)
    1: LINK 47 (MOOSE_STL_SWITCH10 (2,2):5 to MOOSE_STL_SWITCH14 (2,3):6 VL:0)
    2: LINK 52 (MOOSE_STL_SWITCH14 (2,3):5 to MOOSE_STL_SWITCH2 (2,0):6 VL:0)
    3: LINK 55 (MOOSE_STL_SWITCH2 (2,0):1 to MOOSE_STL_SWITCH3 (3,0):2 VL:0)
    4: LINK 63 (MOOSE_STL_SWITCH3 (3,0):6 to MOOSE_STL_SWITCH15 (3,3):5 VL:0)
    5: LINK 123 (MOOSE_STL_SWITCH15 (3,3):6 to MOOSE_STL_SWITCH11 (3,2):5 VL:0)
LINK 54 (MOOSE_STL_SWITCH9 (1,2):1 to MOOSE_STL_SWITCH10 (2,2):2 VL:0) is in a CYCLE of 4:
    0: LINK 54 (MOOSE_STL_SWITCH9 (1,2):1 to MOOSE_STL_SWITCH10 (2,2):2 VL:0)
    1: LINK 48 (MOOSE_STL_SWITCH10 (2,2):1 to MOOSE_STL_SWITCH11 (3,2):2 VL:0)
    2: LINK 124 (MOOSE_STL_SWITCH11 (3,2):1 to MOOSE_STL_SWITCH8 (0,2):2 VL:0)
    3: LINK 127 (MOOSE_STL_SWITCH8 (0,2):1 to MOOSE_STL_SWITCH9 (1,2):2 VL:0)
LINK 56 (MOOSE_STL_SWITCH15 (3,3):2 to MOOSE_STL_SWITCH14 (2,3):1 VL:0) is in a CYCLE of 4:
    0: LINK 56 (MOOSE_STL_SWITCH15 (3,3):2 to MOOSE_STL_SWITCH14 (2,3):1 VL:0)
    1: LINK 52 (MOOSE_STL_SWITCH14 (2,3):5 to MOOSE_STL_SWITCH2 (2,0):6 VL:0)
    2: LINK 55 (MOOSE_STL_SWITCH2 (2,0):1 to MOOSE_STL_SWITCH3 (3,0):2 VL:0)
    3: LINK 63 (MOOSE_STL_SWITCH3 (3,0):6 to MOOSE_STL_SWITCH15 (3,3):5 VL:0)
LINK 64 (MOOSE_STL_SWITCH4 (0,1):2 to MOOSE_STL_SWITCH7 (3,1):1 VL:0) is in a CYCLE of 6:
    0: LINK 64 (MOOSE_STL_SWITCH4 (0,1):2 to MOOSE_STL_SWITCH7 (3,1):1 VL:0)
    1: LINK 51 (MOOSE_STL_SWITCH7 (3,1):2 to MOOSE_STL_SWITCH6 (2,1):1 VL:0)
    2: LINK 58 (MOOSE_STL_SWITCH6 (2,1):2 to MOOSE_STL_SWITCH5 (1,1):1 VL:0)
    3: LINK 79 (MOOSE_STL_SWITCH5 (1,1):6 to MOOSE_STL_SWITCH1 (1,0):5 VL:0)
    4: LINK 86 (MOOSE_STL_SWITCH1 (1,0):2 to MOOSE_STL_SWITCH0 (0,0):1 VL:0)
    5: LINK 89 (MOOSE_STL_SWITCH0 (0,0):7 to MOOSE_STL_SWITCH4 (0,1):8 VL:0)
LINK 68 (MOOSE_STL_SWITCH0 (0,0):2 to MOOSE_STL_SWITCH3 (3,0):1 VL:0) is in a CYCLE of 6:
    0: LINK 68 (MOOSE_STL_SWITCH0 (0,0):2 to MOOSE_STL_SWITCH3 (3,0):1 VL:0)
    1: LINK 46 (MOOSE_STL_SWITCH3 (3,0):2 to MOOSE_STL_SWITCH2 (2,0):1 VL:0)
    2: LINK 50 (MOOSE_STL_SWITCH2 (2,0):5 to MOOSE_STL_SWITCH6 (2,1):6 VL:0)
    3: LINK 58 (MOOSE_STL_SWITCH6 (2,1):2 to MOOSE_STL_SWITCH5 (1,1):1 VL:0)
    4: LINK 79 (MOOSE_STL_SWITCH5 (1,1):6 to MOOSE_STL_SWITCH1 (1,0):5 VL:0)
    5: LINK 86 (MOOSE_STL_SWITCH1 (1,0):2 to MOOSE_STL_SWITCH0 (0,0):1 VL:0)
LINK 70 (MOOSE_STL_SWITCH15 (3,3):5 to MOOSE_STL_SWITCH3 (3,0):6 VL:0) is in a CYCLE of 4:
    0: LINK 70 (MOOSE_STL_SWITCH15 (3,3):5 to MOOSE_STL_SWITCH3 (3,0):6 VL:0)
    1: LINK 11 (MOOSE_STL_SWITCH3 (3,0):1 to MOOSE_STL_SWITCH0 (0,0):2 VL:0)
    2: LINK 82 (MOOSE_STL_SWITCH0 (0,0):6 to MOOSE_STL_SWITCH12 (0,3):5 VL:0)
    3: LINK 112 (MOOSE_STL_SWITCH12 (0,3):2 to MOOSE_STL_SWITCH15 (3,3):1 VL:0)
LINK 71 (MOOSE_STL_SWITCH7 (3,1):8 to MOOSE_STL_SWITCH3 (3,0):7 VL:0) is in a CYCLE of 4:
    0: LINK 71 (MOOSE_STL_SWITCH7 (3,1):8 to MOOSE_STL_SWITCH3 (3,0):7 VL:0)
    1: LINK 10 (MOOSE_STL_SWITCH3 (3,0):3 to MOOSE_STL_SWITCH0 (0,0):4 VL:0)
    2: LINK 89 (MOOSE_STL_SWITCH0 (0,0):7 to MOOSE_STL_SWITCH4 (0,1):8 VL:0)
    3: LINK 92 (MOOSE_STL_SWITCH4 (0,1):4 to MOOSE_STL_SWITCH7 (3,1):3 VL:0)
LINK 75 (MOOSE_STL_SWITCH10 (2,2):8 to MOOSE_STL_SWITCH6 (2,1):7 VL:0) is in a CYCLE of 4:
    0: LINK 75 (MOOSE_STL_SWITCH10 (2,2):8 to MOOSE_STL_SWITCH6 (2,1):7 VL:0)
    1: LINK 22 (MOOSE_STL_SWITCH6 (2,1):8 to MOOSE_STL_SWITCH2 (2,0):7 VL:0)
    2: LINK 66 (MOOSE_STL_SWITCH2 (2,0):6 to MOOSE_STL_SWITCH14 (2,3):5 VL:0)
    3: LINK 73 (MOOSE_STL_SWITCH14 (2,3):8 to MOOSE_STL_SWITCH10 (2,2):7 VL:0)
LINK 81 (MOOSE_STL_SWITCH9 (1,2):6 to MOOSE_STL_SWITCH5 (1,1):5 VL:0) is in a CYCLE of 4:
    0: LINK 81 (MOOSE_STL_SWITCH9 (1,2):6 to MOOSE_STL_SWITCH5 (1,1):5 VL:0)
    1: LINK 13 (MOOSE_STL_SWITCH5 (1,1):1 to MOOSE_STL_SWITCH6 (2,1):2 VL:0)
    2: LINK 42 (MOOSE_STL_SWITCH6 (2,1):5 to MOOSE_STL_SWITCH10 (2,2):6 VL:0)
    3: LINK 49 (MOOSE_STL_SWITCH10 (2,2):2 to MOOSE_STL_SWITCH9 (1,2):1 VL:0)
LINK 84 (MOOSE_STL_SWITCH8 (0,2):6 to MOOSE_STL_SWITCH4 (0,1):5 VL:0) is in a CYCLE of 4:
    0: LINK 84 (MOOSE_STL_SWITCH8 (0,2):6 to MOOSE_STL_SWITCH4 (0,1):5 VL:0)
    1: LINK 9 (MOOSE_STL_SWITCH4 (0,1):6 to MOOSE_STL_SWITCH0 (0,0):5 VL:0)
    2: LINK 82 (MOOSE_STL_SWITCH0 (0,0):6 to MOOSE_STL_SWITCH12 (0,3):5 VL:0)
    3: LINK 119 (MOOSE_STL_SWITCH12 (0,3):6 to MOOSE_STL_SWITCH8 (0,2):5 VL:0)
LINK 85 (MOOSE_STL_SWITCH4 (0,1):8 to MOOSE_STL_SWITCH0 (0,0):7 VL:0) is in a CYCLE of 4:
    0: LINK 85 (MOOSE_STL_SWITCH4 (0,1):8 to MOOSE_STL_SWITCH0 (0,0):7 VL:0)
    1: LINK 69 (MOOSE_STL_SWITCH0 (0,0):4 to MOOSE_STL_SWITCH3 (3,0):3 VL:0)
    2: LINK 78 (MOOSE_STL_SWITCH3 (3,0):7 to MOOSE_STL_SWITCH7 (3,1):8 VL:0)
    3: LINK 95 (MOOSE_STL_SWITCH7 (3,1):3 to MOOSE_STL_SWITCH4 (0,1):4 VL:0)
LINK 88 (MOOSE_STL_SWITCH15 (3,3):7 to MOOSE_STL_SWITCH3 (3,0):8 VL:0) is in a CYCLE of 4:
    0: LINK 88 (MOOSE_STL_SWITCH15 (3,3):7 to MOOSE_STL_SWITCH3 (3,0):8 VL:0)
    1: LINK 10 (MOOSE_STL_SWITCH3 (3,0):3 to MOOSE_STL_SWITCH0 (0,0):4 VL:0)
    2: LINK 83 (MOOSE_STL_SWITCH0 (0,0):8 to MOOSE_STL_SWITCH12 (0,3):7 VL:0)
    3: LINK 109 (MOOSE_STL_SWITCH12 (0,3):4 to MOOSE_STL_SWITCH15 (3,3):3 VL:0)
LINK 91 (MOOSE_STL_SWITCH5 (1,1):8 to MOOSE_STL_SWITCH1 (1,0):7 VL:0) is in a CYCLE of 4:
    0: LINK 91 (MOOSE_STL_SWITCH5 (1,1):8 to MOOSE_STL_SWITCH1 (1,0):7 VL:0)
    1: LINK 4 (MOOSE_STL_SWITCH1 (1,0):1 to MOOSE_STL_SWITCH2 (2,0):2 VL:0)
    2: LINK 37 (MOOSE_STL_SWITCH2 (2,0):7 to MOOSE_STL_SWITCH6 (2,1):8 VL:0)
    3: LINK 44 (MOOSE_STL_SWITCH6 (2,1):4 to MOOSE_STL_SWITCH5 (1,1):3 VL:0)
LINK 94 (MOOSE_STL_SWITCH8 (0,2):8 to MOOSE_STL_SWITCH4 (0,1):7 VL:0) is in a CYCLE of 4:
    0: LINK 94 (MOOSE_STL_SWITCH8 (0,2):8 to MOOSE_STL_SWITCH4 (0,1):7 VL:0)
    1: LINK 92 (MOOSE_STL_SWITCH4 (0,1):4 to MOOSE_STL_SWITCH7 (3,1):3 VL:0)
    2: LINK 104 (MOOSE_STL_SWITCH7 (3,1):7 to MOOSE_STL_SWITCH11 (3,2):8 VL:0)
    3: LINK 106 (MOOSE_STL_SWITCH11 (3,2):3 to MOOSE_STL_SWITCH8 (0,2):4 VL:0)
LINK 99 (MOOSE_STL_SWITCH12 (0,3):3 to MOOSE_STL_SWITCH13 (1,3):4 VL:0) is in a CYCLE of 4:
    0: LINK 99 (MOOSE_STL_SWITCH12 (0,3):3 to MOOSE_STL_SWITCH13 (1,3):4 VL:0)
    1: LINK 96 (MOOSE_STL_SWITCH13 (1,3):8 to MOOSE_STL_SWITCH9 (1,2):7 VL:0)
    2: LINK 98 (MOOSE_STL_SWITCH9 (1,2):4 to MOOSE_STL_SWITCH8 (0,2):3 VL:0)
    3: LINK 115 (MOOSE_STL_SWITCH8 (0,2):7 to MOOSE_STL_SWITCH12 (0,3):8 VL:0)
LINK 101 (MOOSE_STL_SWITCH8 (0,2):3 to MOOSE_STL_SWITCH9 (1,2):4 VL:0) is in a CYCLE of 4:
    0: LINK 101 (MOOSE_STL_SWITCH8 (0,2):3 to MOOSE_STL_SWITCH9 (1,2):4 VL:0)
    1: LINK 25 (MOOSE_STL_SWITCH9 (1,2):8 to MOOSE_STL_SWITCH5 (1,1):7 VL:0)
    2: LINK 100 (MOOSE_STL_SWITCH5 (1,1):4 to MOOSE_STL_SWITCH4 (0,1):3 VL:0)
    3: LINK 102 (MOOSE_STL_SWITCH4 (0,1):7 to MOOSE_STL_SWITCH8 (0,2):8 VL:0)
LINK 103 (MOOSE_STL_SWITCH11 (3,2):8 to MOOSE_STL_SWITCH7 (3,1):7 VL:0) is in a CYCLE of 4:
    0: LINK 103 (MOOSE_STL_SWITCH11 (3,2):8 to MOOSE_STL_SWITCH7 (3,1):7 VL:0)
    1: LINK 95 (MOOSE_STL_SWITCH7 (3,1):3 to MOOSE_STL_SWITCH4 (0,1):4 VL:0)
    2: LINK 102 (MOOSE_STL_SWITCH4 (0,1):7 to MOOSE_STL_SWITCH8 (0,2):8 VL:0)
    3: LINK 108 (MOOSE_STL_SWITCH8 (0,2):4 to MOOSE_STL_SWITCH11 (3,2):3 VL:0)
LINK 111 (MOOSE_STL_SWITCH12 (0,3):1 to MOOSE_STL_SWITCH13 (1,3):2 VL:0) is in a CYCLE of 6:
    0: LINK 111 (MOOSE_STL_SWITCH12 (0,3):1 to MOOSE_STL_SWITCH13 (1,3):2 VL:0)
    1: LINK 18 (MOOSE_STL_SWITCH13 (1,3):5 to MOOSE_STL_SWITCH1 (1,0):6 VL:0)
    2: LINK 86 (MOOSE_STL_SWITCH1 (1,0):2 to MOOSE_STL_SWITCH0 (0,0):1 VL:0)
    3: LINK 90 (MOOSE_STL_SWITCH0 (0,0):5 to MOOSE_STL_SWITCH4 (0,1):6 VL:0)
    4: LINK 102 (MOOSE_STL_SWITCH4 (0,1):7 to MOOSE_STL_SWITCH8 (0,2):8 VL:0)
    5: LINK 115 (MOOSE_STL_SWITCH8 (0,2):7 to MOOSE_STL_SWITCH12 (0,3):8 VL:0)
LINK 121 (MOOSE_STL_SWITCH8 (0,2):5 to MOOSE_STL_SWITCH12 (0,3):6 VL:0) is in a CYCLE of 4:
    0: LINK 121 (MOOSE_STL_SWITCH8 (0,2):5 to MOOSE_STL_SWITCH12 (0,3):6 VL:0)
    1: LINK 112 (MOOSE_STL_SWITCH12 (0,3):2 to MOOSE_STL_SWITCH15 (3,3):1 VL:0)
    2: LINK 123 (MOOSE_STL_SWITCH15 (3,3):6 to MOOSE_STL_SWITCH11 (3,2):5 VL:0)
    3: LINK 124 (MOOSE_STL_SWITCH11 (3,2):1 to MOOSE_STL_SWITCH8 (0,2):2 VL:0)
-------------------------------------------------------------------------------

**Comment by onewayforever** [comment]
Maybe a problem of installation, fixed by just reboot
